baseurl = "https://docs.uchiwa.io/"
languageCode = "en-us"
title = "Uchiwa Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
publishdir = "docs"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-56100759-3"

[params]
# General information
author = "Simon Plourde"
description = "A simple dashboard for the Sensu monitoring framework"
copyright = "Released under the MIT license"

# Repository
provider = "GitHub"
repo_url = "https://github.com/sensu/uchiwa"

version = "0.20.0"
logo = ""
favicon = ""

permalink = "#"

# Custom assets
custom_css = []
custom_js  = []

# Syntax highlighting theme
highlight_css  = ""

[params.palette]
primary = "light-blue"
accent  = "light-blue"

[params.font]
text = "Roboto"
code = "Roboto Mono"

[social]
twitter = "uchiwaio"
github  = "palourde"
email   = "hello@uchiwa.io"

[[menu.main]]
name   = "Home"
url    = "/"
weight = 1

[[menu.main]]
name   = "Getting Started"
url    = "getting-started/"
weight = 10

[[menu.main]]
name   = "Guides"
url    = "guides/"
weight = 20

[[menu.main]]
name   = "Reference"
url    = "reference/"
weight = 30

[[menu.main]]
name   = "API"
url    = "api/"
weight = 40

[[menu.main]]
name   = "Contributing"
url    = "contributing"
weight = 50


[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true
