site_name: Uchiwa Docs
pages:
  - [index.md, Home]
  - [getting-started.md, Installation, Getting Started]
  - [configuration/examples.md, Configuration, Examples]
  - [configuration/sensu.md, Configuration, Sensu settings]
  - [configuration/uchiwa.md, Configuration, Uchiwa settings]
  - [features/collections.md, Features, Collections]
  - [features/health.md, Features, Health]
  - [contributing.md, Contributing, Getting Started]
theme: readthedocs
repo_url: https://github.com/palourde/uchiwa-docs
