site_name: Uchiwa Docs
pages:
  - [index.md, Home]
  - [getting-started.md, Installation, Getting Started]
  - [upgrading.md, Installation, Upgrading]
  - [configuration/overview.md, Configuration, Overview]
  - [configuration/sensu.md, Configuration, Sensu Configuration]
  - [configuration/uchiwa.md, Configuration, Uchiwa Configuration]
  - [features/deleting-check-results.md, Features, Deleting Check Results]
  - [features/federated-api.md, Features, Federated API]
  - [features/issuing-check-requests.md, Features, Issuing Check Requests]
  - [api/health.md, API, Health]
  - [faq/faq.md, FAQ, Frequently Asked Questions]
  - [contributing.md, Contributing, Getting Started]
theme: readthedocs
repo_url: https://github.com/palourde/uchiwa-docs
