site_name: Uchiwa Docs
pages:
  - [index.md, Home]
  - [getting-started.md, Installation, Getting Started]
  - [configuration/overview.md, Configuration, Overview]
  - [configuration/sensu.md, Configuration, Sensu Configuration]
  - [configuration/uchiwa.md, Configuration, Uchiwa Configuration]
  - [faq/faq.md, FAQ, Frequently asked questions]
  - [features/health.md, Features, Health API]
  - [contributing.md, Contributing, Getting Started]
theme: readthedocs
repo_url: https://github.com/palourde/uchiwa-docs
